Update nodejs to 14, fix psql rpm URL
## Description
Fixed 2 problems, appeared while initializing my development environment.
With this PR, I could complete creating my dev environment.

## Description (日本語)
指示通り環境構築をしたところ2つの問題を発見したので、それぞれ修正して環境構築が最後まで行えるようにしました。

- nodeのバージョンが古く、Typescriptの構文エラーが発生していたため、
  - 具体的に発生していたエラーはこれです https://github.com/TypeStrong/ts-node/issues/1218

> /var/www/statink/statink/node_modules/postcss-load-config/node_modules/yaml/dist/compose/composer.js:33
>                 if (prelude[i + 1]?.[0] !== '#')
>                                    ^
>
> SyntaxError: Unexpected token '.'
>     at wrapSafe (internal/modules/cjs/loader.js:915:16)
>     at Module._compile (internal/modules/cjs/loader.js:963:27)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
>     at Module.load (internal/modules/cjs/loader.js:863:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
> (以下略)

- PostgreSQL の rpm のダウンロード URL が404になっていたため、[Wiki](https://github.com/fetus-hina/stat.ink/wiki/How-to-setup-a-development-environment#setup-additional-packages%E8%BF%BD%E5%8A%A0%E3%81%AE%E3%83%91%E3%83%83%E3%82%B1%E3%83%BC%E3%82%B8%E3%81%AE%E3%82%BB%E3%83%83%E3%83%88%E3%82%A2%E3%83%83%E3%83%97)にあった URL に差し替えて PostgreSQL がインストールできるようにしました。

## Need to review
- node は最低動作するバージョンに上げましたが、Latest LTS(=18)にあげても良いかもしれません
- PostgreSQL はとりあえず latest バージョンにしてしまいましたが、バージョンを固定しても良いかもしれません。